package rogatkin.app.remote;


/**
* rogatkin/app/remote/_simple_namingStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public class _simple_namingStub extends org.omg.CORBA.portable.ObjectImpl implements rogatkin.app.remote.simple_naming
{

  public void bind1 (String name, org.omg.CORBA.Object o) throws rogatkin.app.remote.naming_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bind1", true);
                $out.write_string (name);
                org.omg.CORBA.ObjectHelper.write ($out, o);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:rogatkin.app.remote/app/naming_exception:1.0"))
                    throw rogatkin.app.remote.naming_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                bind1 (name, o        );
            } finally {
                _releaseReply ($in);
            }
  } // bind1

  public void unbind1 (String name) throws rogatkin.app.remote.naming_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unbind1", true);
                $out.write_string (name);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:rogatkin.app.remote/app/naming_exception:1.0"))
                    throw rogatkin.app.remote.naming_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                unbind1 (name        );
            } finally {
                _releaseReply ($in);
            }
  } // unbind1

  public org.omg.CORBA.Object lookup1 (String name) throws rogatkin.app.remote.naming_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("lookup1", true);
                $out.write_string (name);
                $in = _invoke ($out);
                org.omg.CORBA.Object $result = org.omg.CORBA.ObjectHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:rogatkin.app.remote/app/naming_exception:1.0"))
                    throw rogatkin.app.remote.naming_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return lookup1 (name        );
            } finally {
                _releaseReply ($in);
            }
  } // lookup1

  public void list1 (String filter, rogatkin.app.remote.bind_listHolder bindings) throws rogatkin.app.remote.naming_exception
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("list1", true);
                $out.write_string (filter);
                $in = _invoke ($out);
                bindings.value = rogatkin.app.remote.bind_listHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:rogatkin.app.remote/app/naming_exception:1.0"))
                    throw rogatkin.app.remote.naming_exceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                list1 (filter, bindings        );
            } finally {
                _releaseReply ($in);
            }
  } // list1

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:rogatkin.app.remote/app/simple_naming:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _simple_namingStub
