package rogatkin.app.remote;


/**
* rogatkin/app/remote/bindHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

abstract public class bindHelper
{
  private static String  _id = "IDL:rogatkin.app.remote/app/bind:1.0";

  public static void insert (org.omg.CORBA.Any a, rogatkin.app.remote.bind that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static rogatkin.app.remote.bind extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ObjectHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "o",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (rogatkin.app.remote.bindHelper.id (), "bind", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static rogatkin.app.remote.bind read (org.omg.CORBA.portable.InputStream istream)
  {
    rogatkin.app.remote.bind value = new rogatkin.app.remote.bind ();
    value.name = istream.read_string ();
    value.o = org.omg.CORBA.ObjectHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, rogatkin.app.remote.bind value)
  {
    ostream.write_string (value.name);
    org.omg.CORBA.ObjectHelper.write (ostream, value.o);
  }

}
