package rogatkin.app.remote;


/**
* rogatkin/app/remote/bind.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public final class bind implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public org.omg.CORBA.Object o = null;

  public bind ()
  {
  } // ctor

  public bind (String _name, org.omg.CORBA.Object _o)
  {
    name = _name;
    o = _o;
  } // ctor

} // class bind
