package rogatkin.app.remote;

/**
* rogatkin/app/remote/naming_exceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public final class naming_exceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public rogatkin.app.remote.naming_exception value = null;

  public naming_exceptionHolder ()
  {
  }

  public naming_exceptionHolder (rogatkin.app.remote.naming_exception initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rogatkin.app.remote.naming_exceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rogatkin.app.remote.naming_exceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rogatkin.app.remote.naming_exceptionHelper.type ();
  }

}
