package rogatkin.app.remote;


/**
* rogatkin/app/remote/naming_exception.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public final class naming_exception extends org.omg.CORBA.UserException
{

  public naming_exception ()
  {
    super(naming_exceptionHelper.id());
  } // ctor


  public naming_exception (String $reason)
  {
    super(naming_exceptionHelper.id() + "  " + $reason);
  } // ctor

} // class naming_exception
