package rogatkin.app.remote;

/**
* rogatkin/app/remote/simple_namingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public final class simple_namingHolder implements org.omg.CORBA.portable.Streamable
{
  public rogatkin.app.remote.simple_naming value = null;

  public simple_namingHolder ()
  {
  }

  public simple_namingHolder (rogatkin.app.remote.simple_naming initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rogatkin.app.remote.simple_namingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rogatkin.app.remote.simple_namingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rogatkin.app.remote.simple_namingHelper.type ();
  }

}
