package rogatkin.app.remote;


/**
* rogatkin/app/remote/simple_namingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public abstract class simple_namingPOA extends org.omg.PortableServer.Servant
 implements rogatkin.app.remote.simple_namingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bind1", new java.lang.Integer (0));
    _methods.put ("unbind1", new java.lang.Integer (1));
    _methods.put ("lookup1", new java.lang.Integer (2));
    _methods.put ("list1", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // app/simple_naming/bind1
       {
         try {
           String name = in.read_string ();
           org.omg.CORBA.Object o = org.omg.CORBA.ObjectHelper.read (in);
           this.bind1 (name, o);
           out = $rh.createReply();
         } catch (rogatkin.app.remote.naming_exception $ex) {
           out = $rh.createExceptionReply ();
           rogatkin.app.remote.naming_exceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // app/simple_naming/unbind1
       {
         try {
           String name = in.read_string ();
           this.unbind1 (name);
           out = $rh.createReply();
         } catch (rogatkin.app.remote.naming_exception $ex) {
           out = $rh.createExceptionReply ();
           rogatkin.app.remote.naming_exceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // app/simple_naming/lookup1
       {
         try {
           String name = in.read_string ();
           org.omg.CORBA.Object $result = null;
           $result = this.lookup1 (name);
           out = $rh.createReply();
           org.omg.CORBA.ObjectHelper.write (out, $result);
         } catch (rogatkin.app.remote.naming_exception $ex) {
           out = $rh.createExceptionReply ();
           rogatkin.app.remote.naming_exceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // app/simple_naming/list1
       {
         try {
           String filter = in.read_string ();
           rogatkin.app.remote.bind_listHolder bindings = new rogatkin.app.remote.bind_listHolder ();
           this.list1 (filter, bindings);
           out = $rh.createReply();
           rogatkin.app.remote.bind_listHelper.write (out, bindings.value);
         } catch (rogatkin.app.remote.naming_exception $ex) {
           out = $rh.createExceptionReply ();
           rogatkin.app.remote.naming_exceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:rogatkin.app.remote/app/simple_naming:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public simple_naming _this() 
  {
    return simple_namingHelper.narrow(
    super._this_object());
  }

  public simple_naming _this(org.omg.CORBA.ORB orb) 
  {
    return simple_namingHelper.narrow(
    super._this_object(orb));
  }


} // class simple_namingPOA
