package rogatkin.app.remote;


/**
* rogatkin/app/remote/simple_naming.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/remotecontext.idl
* Wednesday, February 21, 2018 12:25:09 PM PST
*/

public interface simple_naming extends simple_namingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface simple_naming
